server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
      # 路由id,没有固定规则但要求唯一,建议配合服务名
      - id: payment_route
        # 匹配后提供服务的路由地址
        #uri: http://localhost:8001
        uri: lb://cloud-payment-service
        predicates:
        # 断言,路径相匹配的进行路由
        - Path=/payment/get/**
      - id: payment_route2
        #uri: http://localhost:8001
        uri: lb://cloud-payment-service
        predicates:
        - Path=/payment/lb/**
        # 在该时间之后访问才有效 Before和Between的使用类似
        - After=2020-11-18T00:25:25.078+08:00[Asia/Shanghai]
        # 需要携带此cookie才能访问
        - Cookie=username,vincent
        # 请求头要有X-Request-Id且属性值为整数的正则表达式
        - Header=X-Request-Id, \d+
        # 此外还有Host\Method\Path等


      discovery:
        locator:
          # 开启从注册中心动态创建路由功能,根据微服务名路由
          enabled: true

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka